openapi: 3.0.3
info:
  title: CRAS - OpenAPI 3.0
  description: |-
    This document describes the REST services about the app CRAS (Golden Raspberry Awards) with the maximum and minimuns periods about the producers winners.
    This name is a pun of CRASH.
  termsOfService: http://swagger.io/terms/
  contact:
    email: diegop.ctba@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080
paths:
  /movies/awards:
    get:
      summary: Finds the max and min periods of the winner producers
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RaspberryResponse'          
            application/xml:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieWinner'
        '400':
          description: Invalid status value


components:
  schemas:
    MovieWinner:
      type: object
      properties:
        producer:
          type: String
          example: Producer
        interval:
          type: integer
          format: int64
          example: 1
        previousWin:
          type: integer
          format: int64
          example: 1980
        followingWin:
          type: int64
          format: 1980
      xml:
        name: movie

    RaspberryResponse:
      type: object
      properties:
        min:
          type: array
          xml:
            name: movie
            wrapped: true
          items:
            $ref: '#/components/schemas/MovieWinner'
        max:
          type: array
          xml:
            name: movie
            wrapped: true
          items:
            $ref: '#/components/schemas/MovieWinner'
      xml:
        name: raspberry